sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: wnO0CpjN8tKHixeIyxOBSJwDKfIiVoVi29LuY/3eEFi3QB7XPHl3r/icezLg7YgiBP6EutEOuk9fpxnhIebFqOQD+typu6dDGmMchCXMrjLhhaMcYPPQ6ioHhcIaHkZ93kM0G1i3gcfn1e99COYsHU4n84ntWyu27+K5Mv2GgZI6mhe+Oh+XZNq1zTFnHY6lfVUKOjmJZqRUV8xEXdoRFPaPdHW94JX4NbAedvePEbo2lhgRKQkrdxy7RFtDcwLvu4my2Af5xbOJmWtBMx090tF8wdz/yCXJuVuUjNyATBwDM3dvoVhqEgdl8wHcDzC8jSEqJzubf0FBTAioIKuYgR7I/+18xtO70EEA32yrR+HC7FirkzC0TtJ+NvJilD9Ei5AAspEGvnMhQ33KX+Ud/HzcUe4xE86ZSS2jUoqNkllI9meDJPb6GLE4k+FjxXyYCiXHnuFizjUtC8dGsKKkZ7y9gl0ezN+vXgeX3PIhOb2IT4hzgUijQR/F6TPa6XuJyDDoQ2YWLkbnp2GgTTGlTkvqDILaqYdr5B8gBeADTtyTQQLm+wvo7spUGTbs5hSUS7MEfDDcvpciksvsB8yPdIjTk6IkrkhC+iiwEpgGrKN7EUQGzSMQoMAKPpUhNSbmRvfZh6DRFv7w3hkMJNaDdWCTzkfZGmm6G14u1IpsiLw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Evolution-of-an-Empire-A-Brief-Historical-Sketch-of-England_6134
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy